{
 "title": "Apm v2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Disponibilidade",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"dice-api\", http_status_code=~\"2..\"}[5m])) \r\n/ \r\nsum(rate(http_server_duration_milliseconds_count{exported_job=\"dice-api\"}[5m])) * 100",
     "legendFormat": "Taxa de sucesso"
    }
   ]
  },
  {
   "title": "Response-time P95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{job=\"otel-collector\"}[4m])) by (le))",
     "legendFormat": "response-time"
    }
   ]
  },
  {
   "title": "Response-time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_sum{exported_job=\"dice-api\"}[2m])) / (sum(increase(http_server_duration_milliseconds_count{exported_job=\"dice-api\"}[2m])))",
     "legendFormat": "response-time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{ exported_job=\"dice-api\"}[2m])) ",
     "legendFormat": "Resq/min"
    }
   ]
  },
  {
   "title": "Taxa de erros",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_server_duration_milliseconds_count{http_status_code=~\"4..|5..\"}[5m])) \r\n/ \r\nsum (increase(http_server_duration_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response-time P99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{job=\"otel-collector\"}[5m])) by (le))",
     "legendFormat": "response-time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{ exported_job=\"dice-api\"}[2m])) ",
     "legendFormat": "Resq/min"
    }
   ]
  },
  {
   "title": "Response-time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_sum{exported_job=\"dice-api\"}[2m])) / (sum(increase(http_server_duration_milliseconds_count{exported_job=\"dice-api\"}[2m]))) or vector(0)",
     "legendFormat": "average "
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(http_server_duration_milliseconds_bucket{job=\"otel-collector\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_server_duration_milliseconds_bucket{job=\"otel-collector\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Taxa de erros",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n  increase(http_server_duration_milliseconds_count{http_status_code=~\"4..\"}[2m])\r\n) \r\n/\r\nsum (\r\n  increase(http_server_duration_milliseconds_count[2m])\r\n) or vector(0)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum (increase(http_server_duration_milliseconds_count{http_status_code=~\"5..\"}[2m])) \r\n/ \r\nsum (increase(http_server_duration_milliseconds_count[2m])) or vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Throughput por Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(http_status_code)(increase(http_server_duration_milliseconds_count{exported_job=\"dice-api\"}[2m])) ",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Throughput por Status Code e endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "sum by(http_status_code,http_target)(increase(http_server_duration_milliseconds_count{exported_job=\"dice-api\"}[2m])) ",
     "legendFormat": "{{http_status_code}} - {{http_target}}"
    }
   ]
  },
  { "title": "Infraestrutura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Uso de Memória RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"server\"}[2m])",
     "legendFormat": "Memoria ram"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"server\"}[2m])",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}